# Generated by Django 4.0.1 on 2022-01-24 14:06

from django.db import migrations, models
import midias.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Midias',
            fields=[
                ('id_image', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('information', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to=midias.models.upload_image_midias)),
                ('action', models.CharField(choices=[('NO_FILTER', 'no filter'), ('COLORIZED', 'colorized'), ('GRAYSCALE', 'gray scale'), ('BLURRED', 'blurred'), ('BINARY', 'binary'), ('INVERT', 'invert')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mídia',
                'verbose_name_plural': 'Mídias',
            },
        ),
    ]
